In [8]:
import pandas as pd
path = "GlobalWeather.csv"
df = pd.read_csv(path)
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,5/16/2024 13:15,26.6,79.8,Partly Cloudy,...,8.400,26.600,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,5/16/2024 10:45,19.0,66.2,Partly cloudy,...,1.100,2.000,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,5/16/2024 9:45,23.0,73.4,Sunny,...,10.400,18.400,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,5/16/2024 10:45,6.3,43.3,Light drizzle,...,0.700,0.900,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,5/16/2024 9:45,26.0,78.8,Partly cloudy,...,183.400,262.300,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39589,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1733482800,12/6/2024 7:00,16.2,61.2,Sunny,...,14.430,19.240,1,2,6:33 AM,6:05 PM,11:11 AM,11:08 PM,Waxing Crescent,24
39590,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1733481000,12/6/2024 17:30,21.2,70.2,Partly cloudy,...,99.160,100.825,4,10,6:20 AM,5:15 PM,10:35 AM,9:55 PM,Waxing Crescent,20
39591,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1733481900,12/6/2024 13:45,22.2,71.9,Sunny,...,10.360,31.080,1,1,6:16 AM,5:32 PM,10:39 AM,10:19 PM,Waxing Crescent,21
39592,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1733481900,12/6/2024 12:45,36.0,96.8,Sunny,...,14.245,14.245,1,2,5:28 AM,6:28 PM,9:58 AM,11:06 PM,Waxing Crescent,22
39593,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1733482800,12/6/2024 13:00,34.7,94.4,Sunny,...,12.950,13.505,1,2,5:13 AM,6:21 PM,9:43 AM,10:58 PM,Waxing Crescent,22

## Import Dataset dari Modul

Tahap pertama ataset diimpor menggunakan library Pandas
Library Pandas digunakan untuk membaca dan mengolah data dalam
bentuk DataFrame.

dan File GlobalWeatherRepository.csv dibaca menggunakan fungsi
pd.read_csv().

In [ ]:
df.head(10)
# untuk melihat data utama bsia di custom

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,5/16/2024 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,5/16/2024 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,5/16/2024 9:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,5/16/2024 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,5/16/2024 9:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.12,-61.85,America/Antigua,1715849100,5/16/2024 4:45,26.0,78.8,Partly cloudy,...,1.2,4.5,1,1,5:36 AM,6:32 PM,1:05 PM,1:14 AM,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.59,-58.67,America/Argentina/Buenos_Aires,1715849100,5/16/2024 5:45,8.0,46.4,Clear,...,4.0,5.3,1,1,7:43 AM,5:59 PM,2:36 PM,1:04 AM,Waxing Gibbous,55
7,Armenia,Yerevan,40.18,44.51,Asia/Yerevan,1715849100,5/16/2024 12:45,19.0,66.2,Partly cloudy,...,0.8,0.9,1,1,5:45 AM,8:12 PM,1:17 PM,2:31 AM,Waxing Gibbous,55
8,Australia,Canberra,-35.28,149.22,Australia/Sydney,1715849100,5/16/2024 18:45,9.0,48.2,Clear,...,3.7,5.4,1,1,6:52 AM,5:07 PM,1:31 PM,No moonset,Waxing Gibbous,55
9,Austria,Vienna,48.20,16.37,Europe/Vienna,1715849100,5/16/2024 10:45,16.0,60.8,Partly cloudy,...,3.7,4.4,1,1,5:14 AM,8:29 PM,1:00 PM,2:42 AM,Waxing Gibbous,55

## Menampilkan data teratas

'df.head(10)'
disini saya menampilkan 10 data teratas dari dataset yang sudah di import sebelumnya

In [11]:
df.tail(10)
#untuk melihat data terakhir bsia di custom

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
39584,United Kingdom,London,51.5171,-0.1062,Europe/London,1733481900,12/6/2024 10:45,8.3,46.9,Partly cloudy,...,9.620,15.170,1,1,7:51 AM,3:52 PM,12:06 PM,9:09 PM,Waxing Crescent,23
39585,United States of America,Washington Harbor,48.0792,-123.0439,America/Los_Angeles,1733481900,12/6/2024 2:45,4.7,40.5,Clear,...,9.065,9.805,1,1,7:48 AM,4:19 PM,12:12 PM,10:00 PM,Waxing Crescent,26
39586,Uruguay,Montevideo,-34.8581,-56.1708,America/Montevideo,1733481900,12/6/2024 7:45,18.4,65.1,Light rain,...,14.985,15.540,1,2,5:24 AM,7:48 PM,10:15 AM,No moonset,Waxing Crescent,24
39587,Uzbekistan,Tashkent,41.3167,69.2500,Asia/Tashkent,1733481900,12/6/2024 15:45,7.9,46.1,Sunny,...,64.380,67.710,3,8,7:35 AM,4:54 PM,11:50 AM,9:48 PM,Waxing Crescent,21
39588,Vanuatu,Port Vila,-17.7333,168.3167,Pacific/Efate,1733481000,12/6/2024 21:30,26.2,79.2,Partly cloudy,...,5.735,9.620,1,1,5:03 AM,6:12 PM,9:12 AM,10:32 PM,Waxing Crescent,19
39589,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1733482800,12/6/2024 7:00,16.2,61.2,Sunny,...,14.430,19.240,1,2,6:33 AM,6:05 PM,11:11 AM,11:08 PM,Waxing Crescent,24
39590,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1733481000,12/6/2024 17:30,21.2,70.2,Partly cloudy,...,99.160,100.825,4,10,6:20 AM,5:15 PM,10:35 AM,9:55 PM,Waxing Crescent,20
39591,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1733481900,12/6/2024 13:45,22.2,71.9,Sunny,...,10.360,31.080,1,1,6:16 AM,5:32 PM,10:39 AM,10:19 PM,Waxing Crescent,21
39592,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1733481900,12/6/2024 12:45,36.0,96.8,Sunny,...,14.245,14.245,1,2,5:28 AM,6:28 PM,9:58 AM,11:06 PM,Waxing Crescent,22
39593,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1733482800,12/6/2024 13:00,34.7,94.4,Sunny,...,12.950,13.505,1,2,5:13 AM,6:21 PM,9:43 AM,10:58 PM,Waxing Crescent,22

## Menampilkan data terbawah atau terakhir
'df.tail(10)'
code ini untuk menampilkan 10 data yang terbawah dari dataset tersebut

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Oktovaaaaa\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in C:\Users\Oktovaaaaa\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)

In [ ]:
# menganalisa data dari kolom temperature
df_noid = df.iloc[:,7:]
df_noid

,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012,29.89,0.00,...,8.400,26.600,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012,29.88,0.10,...,1.100,2.000,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,23.0,73.4,Sunny,9.4,15.1,280,W,1011,29.85,0.00,...,10.400,18.400,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007,29.75,0.30,...,0.700,0.900,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011,29.85,0.00,...,183.400,262.300,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39589,16.2,61.2,Sunny,4.0,6.5,158,SSE,1015,29.97,0.00,...,14.430,19.240,1,2,6:33 AM,6:05 PM,11:11 AM,11:08 PM,Waxing Crescent,24
39590,21.2,70.2,Partly cloudy,9.6,15.5,112,ESE,1013,29.91,0.15,...,99.160,100.825,4,10,6:20 AM,5:15 PM,10:35 AM,9:55 PM,Waxing Crescent,20
39591,22.2,71.9,Sunny,9.4,15.1,83,E,1016,30.00,0.00,...,10.360,31.080,1,1,6:16 AM,5:32 PM,10:39 AM,10:19 PM,Waxing Crescent,21
39592,36.0,96.8,Sunny,4.9,7.9,67,ENE,1007,29.75,0.00,...,14.245,14.245,1,2,5:28 AM,6:28 PM,9:58 AM,11:06 PM,Waxing Crescent,22
39593,34.7,94.4,Sunny,6.5,10.4,100,E,1007,29.74,0.00,...,12.950,13.505,1,2,5:13 AM,6:21 PM,9:43 AM,10:58 PM,Waxing Crescent,22

## Mengambil data di kolom 7

Mengambil data dari kolom indeks ke 7 menggunakan fungsi iloc

indeks dimulai dari 0, hingga iloc :,7; 
mengambil semua baris = ;
7 mengambil kolomm dari indeks ke 7 sampai kolom terakhir

dan di simpan ke variabel `df_noid`

In [13]:
df_noid.describe()

,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,precip_mm,precip_in,humidity,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,...,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000,39594.000000
mean,24.350599,75.832651,8.341135,13.427714,172.630853,1013.195914,29.919062,0.151742,0.005783,62.528237,...,19.520155,492.955139,62.538847,12.518648,8.974035,20.754174,39.177234,1.556574,2.260797,47.714856
std,8.130323,14.634566,10.624011,17.097136,101.820087,6.689236,0.197368,0.655896,0.025911,24.769931,...,18.625182,1020.366688,39.559135,24.459390,54.608971,45.741179,99.198453,0.891307,2.232790,35.038713
min,-21.900000,-7.400000,2.200000,3.600000,1.000000,971.000000,28.670000,0.000000,0.000000,2.000000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.185000,0.185000,1.000000,1.000000,0.000000
25%,20.200000,68.400000,4.300000,6.800000,88.000000,1010.000000,29.820000,0.000000,0.000000,44.000000,...,10.800000,212.000000,35.100000,0.740000,0.555000,3.800000,6.600000,1.000000,1.000000,12.000000
50%,26.100000,79.000000,7.200000,11.500000,168.000000,1013.000000,29.910000,0.000000,0.000000,67.000000,...,17.400000,293.700000,57.900000,2.600000,1.850000,10.360000,16.835000,1.000000,1.000000,47.000000
75%,29.200000,84.600000,11.600000,18.700000,258.000000,1016.000000,30.010000,0.030000,0.000000,83.000000,...,26.100000,443.347750,84.400000,11.500000,6.845000,22.940000,38.480000,2.000000,2.000000,82.000000
max,49.200000,120.600000,1841.200000,2963.200000,360.000000,1080.000000,31.890000,42.240000,1.660000,100.000000,...,2970.400000,38879.398000,480.700000,427.700000,400.340000,1614.100000,5554.810000,6.000000,10.000000,100.000000

## Statistik Describe Data

Fungsi `describe` untuk menampilkan ringkasan statistik seperti kolom diatas ini 
count,mean,std,min dan lain lain

In [ ]:
#hanya mengetahui data rata rata tekanan udara dan kelembaban udara
df_noid[['pressure_mb', 'humidity']].mean()

pressure_mb    1013.195914
humidity         62.528237
dtype: float64

## Menghitung Rata-Rata Tekanan dan Kelembaban Udara

Untuk mengetahui nilai rata-rata dari `pressure_mb` dan `humidity`
fungsi `mean()` digunakan untuk menghitung nilai rata-rata
dari masing-masing kolom.

In [16]:
#mengetahui hubungan atau kolerasi antara data
df_noid[['temperature_celsius', 'humidity', 'air_quality_Ozone']].corr()

                     temperature_celsius  humidity  air_quality_Ozone
temperature_celsius             1.000000 -0.420825           0.334880
humidity                       -0.420825  1.000000          -0.508499
air_quality_Ozone               0.334880 -0.508499           1.000000

## Analisis Korelasi

Korelasi digunakan untuk mengetahui hubungan antara dua atau lebih
variabel.

Nilai korelasi berada pada rentang -1 sampai 1:

1 =  korelasi positif.
1 = korelasi negatif.
0 = tidak terdapat korelasi.

Fungsi `.corr()` digunakan untuk menghitung nilai korelasi antar
kolom tersebut.